In [1]:
#Import dependency
import pandas as pd
import re
import numpy as np

In [2]:
#Read in CSV
prod_pd = pd.read_csv("International_energy_production.csv")
prod_pd

,API,Unnamed: 1,1980,1981,1982,1983,1984,1985,1986,1987,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,NaN,total energy production (quad Btu),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,INTL.44-1-WORL-QBTU.A,World,296.3424356,291.2937659,290.128203,293.047718,308.9468834,316.4925296,326.77104,334.398773,...,545.5966162,553.7450243,563.207886,568.3123474,564.492523,579.0744861,600.6668826,611.1215834,586.0864248,606.8165994
2,INTL.44-1-AFG-QBTU.A,Afghanistan,0.072561156,0.092723655,0.095067867,0.09971282,0.099827343,0.12096783,0.120549769,0.114835081,...,0.037492263,0.040816563,0.044789507,0.042057997,0.049505118,0.059500543,0.063175856,0.05530024,0.010260242,0.041213085
3,INTL.44-1-ALB-QBTU.A,Albania,0.15556162,0.158691383,0.205944156,0.234693222,0.191025062,0.191729938,0.196595523,0.202388064,...,0.084037874,0.105636486,0.092961941,0.102254704,0.125356216,0.08259616,0.116337106,0.091399758,0.089594086,0.119993451
4,INTL.44-1-DZA-QBTU.A,Algeria,2.803017355,3.03753686,3.224933779,3.606400483,3.859176003,3.907465538,3.968324779,4.218086334,...,6.99940888,6.510417691,6.561749872,6.696192523,6.910709728,6.830371007,6.755066467,6.474600013,5.972769931,6.656881917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,INTL.4418-1-WAK-QBTU.A,Wake Island,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1620,INTL.4418-1-ESH-QBTU.A,Western Sahara,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1621,INTL.4418-1-YEM-QBTU.A,Yemen,0,0,0,0,0,0,0,0,...,0.000028548,0.000047705,0.0000951,0.001081004,0.00143096,0.001787322,0.004406336,0.00431002,0.00429877,0.005244499
1622,INTL.4418-1-ZMB-QBTU.A,Zambia,0.09359591,0.101143253,0.103630548,0.104463781,0.10213452,0.102923844,0.10127397,0.087029907,...,0.116989704,0.126075766,0.132884219,0.120961589,0.101470417,0.115780904,0.125502418,0.111562837,0.114233794,0.142991022
1623,INTL.4418-1-ZWE-QBTU.A,Zimbabwe,0.041981256,0.043344924,0.038080186,0.039651764,0.036508115,0.032800352,0.033392709,0.026619417,...,0.052395096,0.048852293,0.053437276,0.048243558,0.029787245,0.039124475,0.048907831,0.040075727,0.034551118,0.036331353

In [3]:
print(len(prod_pd))
prod_pd.drop([i for i in range(1161, 1394)], axis=0, inplace=True)
print(len(prod_pd))

1624
1391

In [4]:
prod_pd = prod_pd.dropna(subset=['API'])

In [5]:
split = prod_pd['API'].str.split("-").str[0]
split
prod_pd['Energy Type'] = split

C:\Users\david\AppData\Local\Temp\ipykernel_17788\527509457.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = split

In [6]:
prod_pd

,API,Unnamed: 1,1980,1981,1982,1983,1984,1985,1986,1987,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Energy Type
1,INTL.44-1-WORL-QBTU.A,World,296.3424356,291.2937659,290.128203,293.047718,308.9468834,316.4925296,326.77104,334.398773,...,553.7450243,563.207886,568.3123474,564.492523,579.0744861,600.6668826,611.1215834,586.0864248,606.8165994,INTL.44
2,INTL.44-1-AFG-QBTU.A,Afghanistan,0.072561156,0.092723655,0.095067867,0.09971282,0.099827343,0.12096783,0.120549769,0.114835081,...,0.040816563,0.044789507,0.042057997,0.049505118,0.059500543,0.063175856,0.05530024,0.010260242,0.041213085,INTL.44
3,INTL.44-1-ALB-QBTU.A,Albania,0.15556162,0.158691383,0.205944156,0.234693222,0.191025062,0.191729938,0.196595523,0.202388064,...,0.105636486,0.092961941,0.102254704,0.125356216,0.08259616,0.116337106,0.091399758,0.089594086,0.119993451,INTL.44
4,INTL.44-1-DZA-QBTU.A,Algeria,2.803017355,3.03753686,3.224933779,3.606400483,3.859176003,3.907465538,3.968324779,4.218086334,...,6.510417691,6.561749872,6.696192523,6.910709728,6.830371007,6.755066467,6.474600013,5.972769931,6.656881917,INTL.44
5,INTL.44-1-ASM-QBTU.A,American Samoa,0,0,0,0,0,0,0,0,...,0.000019082,0.00001902,0.000018638,0.000027696,0.000046065,0.00004552,0.000044525,0.000043865,0.000043865,INTL.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,INTL.4418-1-WAK-QBTU.A,Wake Island,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,INTL.4418
1620,INTL.4418-1-ESH-QBTU.A,Western Sahara,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,INTL.4418
1621,INTL.4418-1-YEM-QBTU.A,Yemen,0,0,0,0,0,0,0,0,...,0.000047705,0.0000951,0.001081004,0.00143096,0.001787322,0.004406336,0.00431002,0.00429877,0.005244499,INTL.4418
1622,INTL.4418-1-ZMB-QBTU.A,Zambia,0.09359591,0.101143253,0.103630548,0.104463781,0.10213452,0.102923844,0.10127397,0.087029907,...,0.126075766,0.132884219,0.120961589,0.101470417,0.115780904,0.125502418,0.111562837,0.114233794,0.142991022,INTL.4418
1623,INTL.4418-1-ZWE-QBTU.A,Zimbabwe,0.041981256,0.043344924,0.038080186,0.039651764,0.036508115,0.032800352,0.033392709,0.026619417,...,0.048852293,0.053437276,0.048243558,0.029787245,0.039124475,0.048907831,0.040075727,0.034551118,0.036331353,INTL.4418

In [7]:
prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4411', 'Coal')
prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4413', 'Natural Gas')
prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4415', 'Petroleum')
prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4419', 'Nuclear, Renewables and Other')
prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4417', 'Nuclear')
prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4418', 'Renewables')
prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.44', 'Total Energy Production')
prod_pd

C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4411', 'Coal')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4411', 'Coal')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4413', 'Natural Gas')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4413', 'Natural Gas')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4415', 'Petroleum')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4415', 'Petroleum')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4419', 'Nuclear, Renewables and Other')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4419', 'Nuclear, Renewables and Other')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4417', 'Nuclear')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4417', 'Nuclear')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4418', 'Renewables')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.4418', 'Renewables')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.44', 'Total Energy Production')
C:\Users\david\AppData\Local\Temp\ipykernel_17788\2834912114.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prod_pd['Energy Type'] = prod_pd['Energy Type'].str.replace('INTL.44', 'Total Energy Production')

,API,Unnamed: 1,1980,1981,1982,1983,1984,1985,1986,1987,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Energy Type
1,INTL.44-1-WORL-QBTU.A,World,296.3424356,291.2937659,290.128203,293.047718,308.9468834,316.4925296,326.77104,334.398773,...,553.7450243,563.207886,568.3123474,564.492523,579.0744861,600.6668826,611.1215834,586.0864248,606.8165994,Total Energy Production
2,INTL.44-1-AFG-QBTU.A,Afghanistan,0.072561156,0.092723655,0.095067867,0.09971282,0.099827343,0.12096783,0.120549769,0.114835081,...,0.040816563,0.044789507,0.042057997,0.049505118,0.059500543,0.063175856,0.05530024,0.010260242,0.041213085,Total Energy Production
3,INTL.44-1-ALB-QBTU.A,Albania,0.15556162,0.158691383,0.205944156,0.234693222,0.191025062,0.191729938,0.196595523,0.202388064,...,0.105636486,0.092961941,0.102254704,0.125356216,0.08259616,0.116337106,0.091399758,0.089594086,0.119993451,Total Energy Production
4,INTL.44-1-DZA-QBTU.A,Algeria,2.803017355,3.03753686,3.224933779,3.606400483,3.859176003,3.907465538,3.968324779,4.218086334,...,6.510417691,6.561749872,6.696192523,6.910709728,6.830371007,6.755066467,6.474600013,5.972769931,6.656881917,Total Energy Production
5,INTL.44-1-ASM-QBTU.A,American Samoa,0,0,0,0,0,0,0,0,...,0.000019082,0.00001902,0.000018638,0.000027696,0.000046065,0.00004552,0.000044525,0.000043865,0.000043865,Total Energy Production
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,INTL.4418-1-WAK-QBTU.A,Wake Island,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Renewables
1620,INTL.4418-1-ESH-QBTU.A,Western Sahara,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Renewables
1621,INTL.4418-1-YEM-QBTU.A,Yemen,0,0,0,0,0,0,0,0,...,0.000047705,0.0000951,0.001081004,0.00143096,0.001787322,0.004406336,0.00431002,0.00429877,0.005244499,Renewables
1622,INTL.4418-1-ZMB-QBTU.A,Zambia,0.09359591,0.101143253,0.103630548,0.104463781,0.10213452,0.102923844,0.10127397,0.087029907,...,0.126075766,0.132884219,0.120961589,0.101470417,0.115780904,0.125502418,0.111562837,0.114233794,0.142991022,Renewables
1623,INTL.4418-1-ZWE-QBTU.A,Zimbabwe,0.041981256,0.043344924,0.038080186,0.039651764,0.036508115,0.032800352,0.033392709,0.026619417,...,0.048852293,0.053437276,0.048243558,0.029787245,0.039124475,0.048907831,0.040075727,0.034551118,0.036331353,Renewables

In [8]:
prod_pd.dtypes

API            object
Unnamed: 1     object
1980           object
1981           object
1982           object
1983           object
1984           object
1985           object
1986           object
1987           object
1988           object
1989           object
1990           object
1991           object
1992           object
1993           object
1994           object
1995           object
1996           object
1997           object
1998           object
1999           object
2000           object
2001           object
2002           object
2003           object
2004           object
2005           object
2006           object
2007           object
2008           object
2009           object
2010           object
2011           object
2012           object
2013           object
2014           object
2015           object
2016           object
2017           object
2018           object
2019           object
2020           object
2021           object
Energy Type    object
dtype: object

In [9]:
clean_prod_df = prod_pd.replace('--', '0.0')
clean_prod_df = clean_prod_df.replace('ie', '0.0')
clean_prod_df

,API,Unnamed: 1,1980,1981,1982,1983,1984,1985,1986,1987,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Energy Type
1,INTL.44-1-WORL-QBTU.A,World,296.3424356,291.2937659,290.128203,293.047718,308.9468834,316.4925296,326.77104,334.398773,...,553.7450243,563.207886,568.3123474,564.492523,579.0744861,600.6668826,611.1215834,586.0864248,606.8165994,Total Energy Production
2,INTL.44-1-AFG-QBTU.A,Afghanistan,0.072561156,0.092723655,0.095067867,0.09971282,0.099827343,0.12096783,0.120549769,0.114835081,...,0.040816563,0.044789507,0.042057997,0.049505118,0.059500543,0.063175856,0.05530024,0.010260242,0.041213085,Total Energy Production
3,INTL.44-1-ALB-QBTU.A,Albania,0.15556162,0.158691383,0.205944156,0.234693222,0.191025062,0.191729938,0.196595523,0.202388064,...,0.105636486,0.092961941,0.102254704,0.125356216,0.08259616,0.116337106,0.091399758,0.089594086,0.119993451,Total Energy Production
4,INTL.44-1-DZA-QBTU.A,Algeria,2.803017355,3.03753686,3.224933779,3.606400483,3.859176003,3.907465538,3.968324779,4.218086334,...,6.510417691,6.561749872,6.696192523,6.910709728,6.830371007,6.755066467,6.474600013,5.972769931,6.656881917,Total Energy Production
5,INTL.44-1-ASM-QBTU.A,American Samoa,0,0,0,0,0,0,0,0,...,0.000019082,0.00001902,0.000018638,0.000027696,0.000046065,0.00004552,0.000044525,0.000043865,0.000043865,Total Energy Production
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,INTL.4418-1-WAK-QBTU.A,Wake Island,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Renewables
1620,INTL.4418-1-ESH-QBTU.A,Western Sahara,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Renewables
1621,INTL.4418-1-YEM-QBTU.A,Yemen,0,0,0,0,0,0,0,0,...,0.000047705,0.0000951,0.001081004,0.00143096,0.001787322,0.004406336,0.00431002,0.00429877,0.005244499,Renewables
1622,INTL.4418-1-ZMB-QBTU.A,Zambia,0.09359591,0.101143253,0.103630548,0.104463781,0.10213452,0.102923844,0.10127397,0.087029907,...,0.126075766,0.132884219,0.120961589,0.101470417,0.115780904,0.125502418,0.111562837,0.114233794,0.142991022,Renewables
1623,INTL.4418-1-ZWE-QBTU.A,Zimbabwe,0.041981256,0.043344924,0.038080186,0.039651764,0.036508115,0.032800352,0.033392709,0.026619417,...,0.048852293,0.053437276,0.048243558,0.029787245,0.039124475,0.048907831,0.040075727,0.034551118,0.036331353,Renewables

In [10]:
filter_col = [col for col in clean_prod_df if col.startswith('1')]

for col in filter_col:
    clean_prod_df[col] = clean_prod_df[col].astype(float)

In [11]:
filter_col = [col for col in clean_prod_df if col.startswith('2')]

for col in filter_col:
    clean_prod_df[col] = clean_prod_df[col].astype(float)

In [12]:

clean_prod_df.dtypes

API             object
Unnamed: 1      object
1980           float64
1981           float64
1982           float64
1983           float64
1984           float64
1985           float64
1986           float64
1987           float64
1988           float64
1989           float64
1990           float64
1991           float64
1992           float64
1993           float64
1994           float64
1995           float64
1996           float64
1997           float64
1998           float64
1999           float64
2000           float64
2001           float64
2002           float64
2003           float64
2004           float64
2005           float64
2006           float64
2007           float64
2008           float64
2009           float64
2010           float64
2011           float64
2012           float64
2013           float64
2014           float64
2015           float64
2016           float64
2017           float64
2018           float64
2019           float64
2020           float64
2021           float64
Energy Type     object
dtype: object

In [38]:
clean_prod_df.rename(columns={'Unnamed: 1':"Country"}, inplace = True)
clean_prod_df.dtypes

API             object
Country         object
1980           float64
1981           float64
1982           float64
1983           float64
1984           float64
1985           float64
1986           float64
1987           float64
1988           float64
1989           float64
1990           float64
1991           float64
1992           float64
1993           float64
1994           float64
1995           float64
1996           float64
1997           float64
1998           float64
1999           float64
2000           float64
2001           float64
2002           float64
2003           float64
2004           float64
2005           float64
2006           float64
2007           float64
2008           float64
2009           float64
2010           float64
2011           float64
2012           float64
2013           float64
2014           float64
2015           float64
2016           float64
2017           float64
2018           float64
2019           float64
2020           float64
2021           float64
Energy Type     object
dtype: object

In [44]:
countries_df = clean_prod_df.groupby(['Country',"Energy Type"])
clean_df = countries_df.first()
clean_df.head()

                                                                      API  \
Country             Energy Type
        Afghanistan Coal                           INTL.4411-1-AFG-QBTU.A
                    Natural Gas                    INTL.4413-1-AFG-QBTU.A
                    Nuclear, Renewables and Other  INTL.4419-1-AFG-QBTU.A
                    Petroleum                      INTL.4415-1-AFG-QBTU.A
                    Renewables                     INTL.4418-1-AFG-QBTU.A

                                                       1980      1981  \
Country             Energy Type
        Afghanistan Coal                           0.002355  0.002474
                    Natural Gas                    0.062820  0.082713
                    Nuclear, Renewables and Other  0.007386  0.007537
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.007386  0.007537

                                                       1982      1983  \
Country             Energy Type
        Afghanistan Coal                           0.002870  0.002870
                    Natural Gas                    0.084807  0.088995
                    Nuclear, Renewables and Other  0.007391  0.007848
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.007391  0.007848

                                                       1984      1985  \
Country             Energy Type
        Afghanistan Coal                           0.002929  0.002989
                    Natural Gas                    0.088995  0.109935
                    Nuclear, Renewables and Other  0.007903  0.008044
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.007903  0.008044

                                                       1986      1987  \
Country             Energy Type
        Afghanistan Coal                           0.003167  0.003305
                    Natural Gas                    0.109935  0.103653
                    Nuclear, Renewables and Other  0.007448  0.007877
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.007448  0.007877

                                                       1988  ...      2012  \
Country             Energy Type                              ...
        Afghanistan Coal                           0.002731  ...  0.024542
                    Natural Gas                    0.110982  ...  0.005927
                    Nuclear, Renewables and Other  0.007681  ...  0.007023
                    Petroleum                      0.000000  ...  0.000000
                    Renewables                     0.007681  ...  0.007023

                                                       2013      2014  \
Country             Energy Type
        Afghanistan Coal                           0.026660  0.030033
                    Natural Gas                    0.005713  0.005247
                    Nuclear, Renewables and Other  0.008444  0.009510
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.008444  0.009510

                                                       2015      2016  \
Country             Energy Type
        Afghanistan Coal                           0.027016  0.033607
                    Natural Gas                    0.005406  0.006112
                    Nuclear, Renewables and Other  0.009636  0.009786
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.009636  0.009786

                                                       2017      2018  \
Country             Energy Type
        Afghanistan Coal                           0.043365  0.048392
                    Natural Gas                    0.006112  0.005998
                    Nuclear, Renewables and Other  0.010024  0.008785
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.010024  0.008785

                                                       2019      2020  \
Country             Energy Type
        Afghanistan Coal                           0.042336  0.001128
                    Natural Gas                    0.005039  0.003140
                    Nuclear, Renewables and Other  0.007925  0.005992
                    Petroleum                      0.000000  0.000000
                    Renewables                     0.007925  0.005992

                                                       2021
Country             Energy Type
        Afghanistan Coal                           0.031959
                    Natural Gas                    0.003140
                    Nuclear, Renewables and Other  0.006114
                    Petroleum                      0.000000
                    Renewables                     0.006114

[5 rows x 43 columns]

In [43]:
clean_df.to_csv("Clean International Energy Production.csv")