In [1]:
#Import dependency
import pandas as pd
import re
import numpy as np

In [2]:
prod_df = pd.read_csv('Clean International Energy Production.csv')
prod_df

,Country,Energy Type,API,1980,1981,1982,1983,1984,1985,1986,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Afghanistan,Coal,INTL.4411-1-AFG-QBTU.A,0.002355,0.002474,0.002870,0.002870,0.002929,0.002989,0.003167,...,0.024542,0.026660,0.030033,0.027016,0.033607,0.043365,0.048392,0.042336,0.001128,0.031959
1,Afghanistan,Natural Gas,INTL.4413-1-AFG-QBTU.A,0.062820,0.082713,0.084807,0.088995,0.088995,0.109935,0.109935,...,0.005927,0.005713,0.005247,0.005406,0.006112,0.006112,0.005998,0.005039,0.003140,0.003140
2,Afghanistan,"Nuclear, Renewables and Other",INTL.4419-1-AFG-QBTU.A,0.007386,0.007537,0.007391,0.007848,0.007903,0.008044,0.007448,...,0.007023,0.008444,0.009510,0.009636,0.009786,0.010024,0.008785,0.007925,0.005992,0.006114
3,Afghanistan,Petroleum,INTL.4415-1-AFG-QBTU.A,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Afghanistan,Renewables,INTL.4418-1-AFG-QBTU.A,0.007386,0.007537,0.007391,0.007848,0.007903,0.008044,0.007448,...,0.007023,0.008444,0.009510,0.009636,0.009786,0.010024,0.008785,0.007925,0.005992,0.006114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1380,World,Coal,INTL.4411-1-WORL-QBTU.A,80.117704,80.461549,83.395337,83.674348,87.679784,91.692644,94.044983,...,169.342659,172.137136,171.939639,168.036483,158.115927,162.389321,168.702042,172.530788,164.939295,172.917464
1381,World,Natural Gas,INTL.4413-1-WORL-QBTU.A,54.761046,55.573537,55.495523,56.115952,61.758598,64.124523,65.328648,...,123.533191,125.031915,126.990053,129.644515,130.876105,137.140693,144.003859,149.016934,144.619656,151.056127
1382,World,"Nuclear, Renewables and Other",INTL.4419-1-WORL-QBTU.A,28.352578,29.819730,31.474538,33.988222,36.954675,39.540573,40.848563,...,75.010973,78.955642,82.014756,83.194395,86.945789,90.544503,94.649310,97.329781,97.028042,101.017005
1383,World,Petroleum,INTL.4415-1-WORL-QBTU.A,133.111109,125.438950,119.762805,119.269196,122.553827,121.134790,126.548845,...,177.709793,177.620331,182.263438,187.436953,188.554702,188.999969,193.311672,192.244079,179.499431,181.826004
1384,World,Total Energy Production,INTL.44-1-WORL-QBTU.A,296.342436,291.293766,290.128203,293.047718,308.946883,316.492530,326.771040,...,545.596616,553.745024,563.207886,568.312347,564.492523,579.074486,600.666883,611.121583,586.086425,606.816599

In [3]:
gdp_df = pd.read_csv("International_GDP_Clean.csv")
gdp_df

,Unnamed: 0,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
0,,1.980000e+03,1.981000e+03,1.982000e+03,1.983000e+03,1.984000e+03,1.985000e+03,1.986000e+03,1.987000e+03,1.988000e+03,...,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2.017000e+03,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03
1,Afghanistan,3.641723e+09,3.478788e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
2,Albania,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.857338e+09,1.897050e+09,2.097326e+09,2.080796e+09,2.051236e+09,...,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.825579e+10
3,Algeria,4.234638e+10,4.434867e+10,4.520709e+10,4.880137e+10,5.369828e+10,5.793787e+10,6.369224e+10,6.674640e+10,5.908907e+10,...,2.090590e+11,2.097550e+11,2.138100e+11,1.659793e+11,1.600342e+11,1.700970e+11,1.749109e+11,1.717674e+11,1.450092e+11,1.630444e+11
4,American Samoa,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.400000e+08,6.380000e+08,6.430000e+08,6.730000e+08,6.710000e+08,6.120000e+08,6.390000e+08,6.470000e+08,7.160000e+08,7.090000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,Sub-Saharan Africa,2.810142e+11,3.880724e+11,3.566257e+11,3.139038e+11,2.748923e+11,2.537029e+11,2.604549e+11,2.962527e+11,3.124164e+11,...,1.707695e+12,1.814869e+12,1.895925e+12,1.690061e+12,1.579959e+12,1.712749e+12,1.782359e+12,1.803363e+12,1.719010e+12,1.929052e+12
263,Sub-Saharan Africa (excluding high income),2.808714e+11,3.879272e+11,3.564864e+11,3.137639e+11,2.747457e+11,2.535369e+11,2.602483e+11,2.960043e+11,3.121326e+11,...,1.706636e+12,1.813541e+12,1.894537e+12,1.688645e+12,1.578467e+12,1.711174e+12,1.780721e+12,1.801677e+12,1.717750e+12,1.927599e+12
264,Sub-Saharan Africa (IDA & IBRD countries),2.810142e+11,3.880724e+11,3.566257e+11,3.139038e+11,2.748923e+11,2.537029e+11,2.604549e+11,2.962527e+11,3.124164e+11,...,1.707695e+12,1.814869e+12,1.895925e+12,1.690061e+12,1.579959e+12,1.712749e+12,1.782359e+12,1.803363e+12,1.719010e+12,1.929052e+12
265,Upper middle income,1.658117e+12,1.792584e+12,1.711731e+12,1.626146e+12,1.674642e+12,1.713511e+12,1.734387e+12,1.850902e+12,2.052565e+12,...,1.891479e+13,2.030664e+13,2.093960e+13,1.966354e+13,1.954982e+13,2.164484e+13,2.330450e+13,2.368174e+13,2.285137e+13,2.710409e+13
266,World,1.133659e+13,1.172760e+13,1.160977e+13,1.184007e+13,1.227160e+13,1.286213e+13,1.520774e+13,1.731021e+13,1.934119e+13,...,7.550039e+13,7.760623e+13,7.973264e+13,7.518636e+13,7.646936e+13,8.140950e+13,8.646696e+13,8.765425e+13,8.511634e+13,9.652743e+13

In [4]:
gdp_df= gdp_df.drop(index = 0)
gdp_df

,Unnamed: 0,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
1,Afghanistan,3.641723e+09,3.478788e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
2,Albania,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.857338e+09,1.897050e+09,2.097326e+09,2.080796e+09,2.051236e+09,...,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.825579e+10
3,Algeria,4.234638e+10,4.434867e+10,4.520709e+10,4.880137e+10,5.369828e+10,5.793787e+10,6.369224e+10,6.674640e+10,5.908907e+10,...,2.090590e+11,2.097550e+11,2.138100e+11,1.659793e+11,1.600342e+11,1.700970e+11,1.749109e+11,1.717674e+11,1.450092e+11,1.630444e+11
4,American Samoa,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.400000e+08,6.380000e+08,6.430000e+08,6.730000e+08,6.710000e+08,6.120000e+08,6.390000e+08,6.470000e+08,7.160000e+08,7.090000e+08
5,Andorra,4.464161e+08,3.889587e+08,3.758960e+08,3.278618e+08,3.300707e+08,3.467380e+08,4.820006e+08,6.113164e+08,7.214259e+08,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,Sub-Saharan Africa,2.810142e+11,3.880724e+11,3.566257e+11,3.139038e+11,2.748923e+11,2.537029e+11,2.604549e+11,2.962527e+11,3.124164e+11,...,1.707695e+12,1.814869e+12,1.895925e+12,1.690061e+12,1.579959e+12,1.712749e+12,1.782359e+12,1.803363e+12,1.719010e+12,1.929052e+12
263,Sub-Saharan Africa (excluding high income),2.808714e+11,3.879272e+11,3.564864e+11,3.137639e+11,2.747457e+11,2.535369e+11,2.602483e+11,2.960043e+11,3.121326e+11,...,1.706636e+12,1.813541e+12,1.894537e+12,1.688645e+12,1.578467e+12,1.711174e+12,1.780721e+12,1.801677e+12,1.717750e+12,1.927599e+12
264,Sub-Saharan Africa (IDA & IBRD countries),2.810142e+11,3.880724e+11,3.566257e+11,3.139038e+11,2.748923e+11,2.537029e+11,2.604549e+11,2.962527e+11,3.124164e+11,...,1.707695e+12,1.814869e+12,1.895925e+12,1.690061e+12,1.579959e+12,1.712749e+12,1.782359e+12,1.803363e+12,1.719010e+12,1.929052e+12
265,Upper middle income,1.658117e+12,1.792584e+12,1.711731e+12,1.626146e+12,1.674642e+12,1.713511e+12,1.734387e+12,1.850902e+12,2.052565e+12,...,1.891479e+13,2.030664e+13,2.093960e+13,1.966354e+13,1.954982e+13,2.164484e+13,2.330450e+13,2.368174e+13,2.285137e+13,2.710409e+13
266,World,1.133659e+13,1.172760e+13,1.160977e+13,1.184007e+13,1.227160e+13,1.286213e+13,1.520774e+13,1.731021e+13,1.934119e+13,...,7.550039e+13,7.760623e+13,7.973264e+13,7.518636e+13,7.646936e+13,8.140950e+13,8.646696e+13,8.765425e+13,8.511634e+13,9.652743e+13

In [5]:
gdp_df.rename(columns = {'Unnamed: 0': 'Country'}, inplace = True)

In [6]:
gdp_df

,Country,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,...,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0
1,Afghanistan,3.641723e+09,3.478788e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.020357e+10,2.056449e+10,2.055058e+10,1.999816e+10,1.801956e+10,1.889635e+10,1.841885e+10,1.890449e+10,2.014344e+10,1.478686e+10
2,Albania,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.857338e+09,1.897050e+09,2.097326e+09,2.080796e+09,2.051236e+09,...,1.231983e+10,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.515643e+10,1.540183e+10,1.513187e+10,1.825579e+10
3,Algeria,4.234638e+10,4.434867e+10,4.520709e+10,4.880137e+10,5.369828e+10,5.793787e+10,6.369224e+10,6.674640e+10,5.908907e+10,...,2.090590e+11,2.097550e+11,2.138100e+11,1.659793e+11,1.600342e+11,1.700970e+11,1.749109e+11,1.717674e+11,1.450092e+11,1.630444e+11
4,American Samoa,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,6.400000e+08,6.380000e+08,6.430000e+08,6.730000e+08,6.710000e+08,6.120000e+08,6.390000e+08,6.470000e+08,7.160000e+08,7.090000e+08
5,Andorra,4.464161e+08,3.889587e+08,3.758960e+08,3.278618e+08,3.300707e+08,3.467380e+08,4.820006e+08,6.113164e+08,7.214259e+08,...,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.155065e+09,2.891022e+09,3.330282e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,Sub-Saharan Africa,2.810142e+11,3.880724e+11,3.566257e+11,3.139038e+11,2.748923e+11,2.537029e+11,2.604549e+11,2.962527e+11,3.124164e+11,...,1.707695e+12,1.814869e+12,1.895925e+12,1.690061e+12,1.579959e+12,1.712749e+12,1.782359e+12,1.803363e+12,1.719010e+12,1.929052e+12
263,Sub-Saharan Africa (excluding high income),2.808714e+11,3.879272e+11,3.564864e+11,3.137639e+11,2.747457e+11,2.535369e+11,2.602483e+11,2.960043e+11,3.121326e+11,...,1.706636e+12,1.813541e+12,1.894537e+12,1.688645e+12,1.578467e+12,1.711174e+12,1.780721e+12,1.801677e+12,1.717750e+12,1.927599e+12
264,Sub-Saharan Africa (IDA & IBRD countries),2.810142e+11,3.880724e+11,3.566257e+11,3.139038e+11,2.748923e+11,2.537029e+11,2.604549e+11,2.962527e+11,3.124164e+11,...,1.707695e+12,1.814869e+12,1.895925e+12,1.690061e+12,1.579959e+12,1.712749e+12,1.782359e+12,1.803363e+12,1.719010e+12,1.929052e+12
265,Upper middle income,1.658117e+12,1.792584e+12,1.711731e+12,1.626146e+12,1.674642e+12,1.713511e+12,1.734387e+12,1.850902e+12,2.052565e+12,...,1.891479e+13,2.030664e+13,2.093960e+13,1.966354e+13,1.954982e+13,2.164484e+13,2.330450e+13,2.368174e+13,2.285137e+13,2.710409e+13
266,World,1.133659e+13,1.172760e+13,1.160977e+13,1.184007e+13,1.227160e+13,1.286213e+13,1.520774e+13,1.731021e+13,1.934119e+13,...,7.550039e+13,7.760623e+13,7.973264e+13,7.518636e+13,7.646936e+13,8.140950e+13,8.646696e+13,8.765425e+13,8.511634e+13,9.652743e+13

In [7]:
renew_df = prod_df[prod_df["Energy Type"]=="Renewables"][["Country", "Energy Type", "2011"]]

In [25]:
gdp11 = gdp_df[["Country", "2011.0"]]

In [26]:
gdp11 = gdp11.rename(columns= {"2011.0":"2011_gdp"})
renew_df = renew_df.rename(columns= {"2011":"2011_renew"})

In [27]:
gdp21["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'British Virgin Islands',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands',
       'Central African Republic', 'Chad', 'Channel Islands', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
       'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Polynesia',
       'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Gibraltar',
       'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Kiribati', "Korea, Dem. People's Rep.", 'Korea, Rep.', 'Kosovo',
       'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Macao SAR, China', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.',
       'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Northern Mariana Islands',
       'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Romania',
       'Russian Federation', 'Rwanda', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovak Republic', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia',
       'St. Martin (French part)', 'St. Vincent and the Grenadines',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand',
       'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela, RB', 'Vietnam', 'Virgin Islands (U.S.)',
       'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe',
       'Africa Eastern and Southern', 'Africa Western and Central',
       'Arab World', 'Caribbean small states',
       'Central Europe and the Baltics', 'Early-demographic dividend',
       'East Asia & Pacific',
       'East Asia & Pacific (excluding high income)',
       'East Asia & Pacific (IDA & IBRD countries)', 'Euro area',
       'Europe & Central Asia',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia (IDA & IBRD countries)', 'European Union',
       'Fragile and conflict affected situations',
       'Heavily indebted poor countries (HIPC)', 'High income',
       'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only',
       'IDA total', 'Late-demographic dividend',
       'Latin America & Caribbean',
       'Latin America & Caribbean (excluding high income)',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Least developed countries: UN classification',
       'Low & middle income', 'Low income', 'Lower middle income',
       'Middle East & North Africa',
       'Middle East & North Africa (excluding high income)',
       'Middle East & North Africa (IDA & IBRD countries)',
       'Middle income', 'North America', 'Not classified', 'OECD members',
       'Other small states', 'Pacific island small states',
       'Post-demographic dividend', 'Pre-demographic dividend',
       'Small states', 'South Asia', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Upper middle income',
       'World'], dtype=object)

In [28]:
renew_df["Country"] = renew_df["Country"].str.strip()

In [29]:
temp = renew_df.merge(gdp21, left_on = ["Country"], right_on = ["Country"], how = "left")

In [30]:
temp[temp["2011_gdp"].isna()]

,Country,Energy Type,2011_renew,matches,2011_gdp
5,Antarctica,Renewables,3.886400e-05,,NaN
27,Brunei,Renewables,0.000000e+00,Brunei Darussalam,NaN
30,Burma,Renewables,7.235117e-02,,NaN
43,Congo-Brazzaville,Renewables,7.608600e-03,"Congo, Rep.",NaN
44,Congo-Kinshasa,Renewables,7.513383e-02,,NaN
45,Cook Islands,Renewables,9.720000e-07,"British Virgin Islands, Northern Mariana Islands",NaN
51,Côte d’Ivoire,Renewables,1.708073e-02,Cote d'Ivoire,NaN
57,Egypt,Renewables,1.456889e-01,"Egypt, Arab Rep.",NaN
64,Falkland Islands,Renewables,5.829600e-05,"Northern Mariana Islands, Turks and Caicos Isl...",NaN
68,Former Czechoslovakia,Renewables,0.000000e+00,,NaN
69,Former Serbia and Montenegro,Renewables,0.000000e+00,"Montenegro, Serbia",NaN
70,Former U.S.S.R.,Renewables,0.000000e+00,"Korea, Dem. People's Rep.",NaN
71,Former Yugoslavia,Renewables,0.000000e+00,Latvia,NaN
73,French Guiana,Renewables,6.791484e-03,St. Martin (French part),NaN
79,"Germany, East",Renewables,0.000000e+00,"Germany, East Asia & Pacific (excluding high i...",NaN
80,"Germany, West",Renewables,0.000000e+00,Germany,NaN
86,Guadeloupe,Renewables,2.263828e-03,,NaN
93,Hawaiian Trade Zone,Renewables,0.000000e+00,,NaN
95,Hong Kong,Renewables,1.590759e-03,"Hong Kong SAR, China",NaN
100,Iran,Renewables,1.188394e-01,"Iran, Islamic Rep.",NaN
113,Kyrgyzstan,Renewables,1.360046e-01,,NaN
114,Laos,Renewables,1.247437e-01,,NaN
122,Macau,Renewables,0.000000e+00,,NaN
129,Martinique,Renewables,1.554560e-04,,NaN
133,Micronesia,Renewables,0.000000e+00,"Micronesia, Fed. Sts.",NaN
137,Montserrat,Renewables,0.000000e+00,,NaN
144,Netherlands Antilles,Renewables,8.663850e-04,Netherlands,NaN
150,Niue,Renewables,0.000000e+00,,NaN
151,North Korea,Renewables,1.270017e-01,"Korea, Dem. People's Rep., Middle East & North...",NaN
157,Palestinian Territories,Renewables,0.000000e+00,,NaN
167,Reunion,Renewables,8.064280e-03,,NaN
169,Russia,Renewables,1.643442e+00,Russian Federation,NaN
171,Saint Helena,Renewables,0.000000e+00,,NaN
172,Saint Kitts and Nevis,Renewables,4.858000e-05,"St. Kitts and Nevis, Fragile and conflict affe...",NaN
173,Saint Lucia,Renewables,0.000000e+00,St. Lucia,NaN
174,Saint Pierre and Miquelon,Renewables,1.943200e-05,Fragile and conflict affected situations,NaN
175,Saint Vincent/Grenadines,Renewables,2.429000e-04,St. Vincent and the Grenadines,NaN
184,Slovakia,Renewables,5.088347e-02,,NaN
189,South Korea,Renewables,9.385473e-02,"Korea, Dem. People's Rep., South Asia (IDA & I...",NaN
197,Syria,Renewables,3.189763e-02,Syrian Arab Republic,NaN
198,Taiwan,Renewables,8.731831e-02,,NaN
202,The Bahamas,Renewables,5.829600e-06,"Bahamas, The, St. Vincent and the Grenadines",NaN
212,U.S. Pacific Islands,Renewables,0.000000e+00,"Faroe Islands, East Asia & Pacific (excluding ...",NaN
213,U.S. Territories,Renewables,0.000000e+00,"Korea, Dem. People's Rep.",NaN
214,U.S. Virgin Islands,Renewables,6.704040e-06,"Virgin Islands (U.S.), British Virgin Islands",NaN
223,Venezuela,Renewables,8.048249e-01,"Venezuela, RB",NaN
225,Wake Island,Renewables,0.000000e+00,Pacific island small states,NaN
226,Western Sahara,Renewables,0.000000e+00,Africa Western and Central,NaN
227,Yemen,Renewables,1.943200e-05,"Yemen, Rep.",NaN

In [31]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [32]:
def fuzzy_merge(df_1, df_2, key1, key2, threshold=90, limit=2):
    """
    :param df_1: the left table to join
    :param df_2: the right table to join
    :param key1: key column of the left table
    :param key2: key column of the right table
    :param threshold: how close the matches should be to return a match, based on Levenshtein distance
    :param limit: the amount of matches that will get returned, these are sorted high to low
    :return: dataframe with boths keys and matches
    """
    s = df_2[key2].tolist()
    
    m = df_1[key1].apply(lambda x: process.extract(x, s, limit=limit))    
    df_1['matches'] = m
    
    m2 = df_1['matches'].apply(lambda x: ', '.join([i[0] for i in x if i[1] >= threshold]))
    df_1['matches'] = m2
    
    return df_1

In [33]:
renew_df = fuzzy_merge(renew_df, gdp21, 'Country', 'Country', 80)

In [34]:
renew_df = pd.DataFrame(renew_df)

In [35]:
gdp11= gdp11.rename(columns = {'Country': "matches"})

In [36]:
renew_df = renew_df.merge(gdp11, left_on = ["matches"], right_on = ["matches"], how = "left")

In [37]:
gdp11= gdp11.rename(columns = {'matches': "Country", "2011_gdp": "extra_gdp"})

In [38]:
renew_df = renew_df.merge(gdp11, left_on = ["Country"], right_on = ["Country"], how = "left")

In [39]:
renew_df["2011_gdp"]= np.where(renew_df["2011_gdp"].isna(), renew_df["extra_gdp"], renew_df["2011_gdp"])

In [40]:
renew_df = renew_df.drop(columns = ["extra_gdp"])

In [42]:
renew_df = renew_df.drop(columns = ["Country", "Energy Type", "matches"])

In [44]:
renew_df.dtypes

2011_renew    float64
2011_gdp      float64
dtype: object

In [45]:
renew1_df = renew_df[np.isfinite(renew_df).all(1)]

In [46]:
print(renew1_df)

     2011_renew      2011_gdp
0      0.005784  1.819041e+10
1      0.039753  1.289076e+10
2      0.004830  2.000131e+11
3      0.000000  5.700000e+08
4      0.038650  1.094366e+11
..          ...           ...
225    0.000000  7.737746e+09
226    0.000000  6.804560e+11
227    0.000019  3.272642e+10
228    0.111087  2.345952e+10
229    0.051304  1.410192e+10

[203 rows x 2 columns]

In [47]:
renew1_df.to_csv('2011_Renewable_GDP.csv')